### ISSUE TITLE
piskapopa

### ISSUE THREAD

**Issue by gingersamurai** [de1phin/iam#35]
https://github.com/de1phin/iam/blob/c0f3301e9b1297e42bbce9d13ba931658121c15b/infra/k8s/token-service/deployment.yaml#L16

**Comment by Nifacy** [comment]
Ребят, я новенький, можете на меня эту тасочку кинуть 😊😊😊😊

**Comment by gingersamurai** [comment]
какую тасочку ты с ума сошел
